services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-server
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - order-app-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-server
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - order-app-net

  order-consumer:
      build:
        context: ./order-consumer
      image: order-consumer:0.1
      container_name: order-consumer
      depends_on:
        - kafka
      environment:
        KAFKA_BOOTSTRAP_SERVER: kafka-server:9092
        KAFKA_TOPIC: orders
        DB_USER: martec
        DB_PASSWORD: dev1234
        DB_DSN: oracle-db:1521/FREEPDB1
      networks:
        - order-app-net

  order-producer:
    build:
      context: ./order-producer
    image: order-producer:0.1
    container_name: order-producer
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka-server:9092
      KAFKA_TOPIC: orders
    networks:
      - order-app-net

networks:
  order-app-net:
    driver: bridge
#    external: true